### ISSUE TITLE
Signup Page

### ISSUE THREAD

**Issue by Angham116** [FACG6/Gaza-Freelancing-Community#12]
#### Sign up Page
*  View SignUp page for the user.

#### Acceptance Criteria
---
  - [ ]  prepare html file.
  - [ ] prepare css file.
  - [ ] prepare signUpDom.js file.
    - [x] use ``` collectData() ``` function. 
    - [ ]  use ``` checkValidation() ``` function.
    - [ ]  send request to the back-end by fetch with ``` /signup ``` route.
  - [x] Testing.

#### User data Validation 
------
on the dom file 
 Using ``` checkValidation() ``` that contains an object of ``` userData ``` and make sure that shouldn't be empty and all input fields with at least 1 char and no more than 250 char.

#### The shape of the ideal request body on the fetch function : 
----

```
userData = { 
    firstSection : {
                  firstname : 'Angham',
                  lastname : 'Aabed',
                  mobile_number : '0097234567',
                  email : 'a@gmail.com',
                   },
   secondSection : {
                 specalization_id : 1, 
                 freelancer_url : 'https://github.com/angham',
                 photo_url : 'https://www.iconspng.com/image/36709/face-avatar-man-male-handsome-3',
                 },
   thirdSection : {
                password : 'a123456',
                 }
    }
```

**Comment by Angham116** [comment]
@knanahassouna1
