### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by Angham116** [FACG6/Gaza-Freelancing-Community#20]
#### Profile Page
* View Profile page for the user.

#### Acceptance Criteria
---
  - [x]  prepare html file 

  - [x] prepare css file 
     - [x] send request to the back-end by fetch with ``` /profile ``` route and method ``` GET ```

  - [x] Testing
