### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Angham116** [FACG6/Gaza-Freelancing-Community#22]
#### Home Page
* View home page for the user with all users proposals.

#### Acceptance Criteria
---
  - [ ]  prepare html file 

  - [ ] prepare css file 
     - [ ] send request to the back-end by fetch with ``` /``` route and method ``` GET ```

  - [ ] Testing
